apiVersion: v1
kind: Service
metadata:
  name: generics-travel
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: generics-travel
  type: NodePort
