#!/usr/bin/env bash

source .env

eb setenv \
  MTA_FEED_API_KEY=$MTA_FEED_API_KEY \
  MTA_FEED_IDS=$MTA_FEED_IDS \
  MTA_FEED_REFRESH_INTERVAL=$MTA_FEED_REFRESH_INTERVAL \
  MTA_FEED_ROOT_URL=$MTA_FEED_ROOT_URL \
  RANGE_X_START=$RANGE_X_START \
  RANGE_X_STOP=$RANGE_X_STOP \
  RANGE_Y_START=$RANGE_Y_START \
  RANGE_Y_STOP=$RANGE_Y_STOP \
  WS_HOST=$WS_HOST \
  WS_PORT=$WS_PORT \
  --environment generics-travel-dev
